import { createContext, useCallback, useContext, useState } from 'react';

const translations = {
  uz: {
    home: 'Bosh sahifa',
    about: 'Biz haqimizda',
    products: 'Mahsulotlar',
    news: 'Yangiliklar',
    promotions: 'Aksiyalar',
    contacts: 'Kontaktlar',
    login: 'Kirish',
    register: "Ro'yxatdan o'tish",
    cart: 'Savatcha',
    profile: 'Profil',
    search: 'Qidirish...',
    adminPanel: 'Admin panel',
    logout: 'Chiqish',

    heroTitle1: 'Sanoat va agrosanoat uchun',
    heroTitle2: 'innovatsion polimer',
    heroTitle3: 'yechimlar',
    heroSubtitle: "2005-yildan buyon Markaziy Osiyo bozori uchun yuqori sifatli polimer mahsulotlari ishlab chiqaramiz.",

    techSolutions: 'Texnologik yechimlar',
    techDesc: "Global sanoat talablariga mos, yuqori fizik-mexanik ko'rsatkichli polimer mahsulotlar.",
    agroTitle: 'Agrosanoat komplekslari',
    thermoTitle: 'Termo qadoqlash (Shrink)',
    logisticsTitle: 'Sanoat logistika paketlari',
    moreParams: 'Batafsil ',
    onlineCatalog: 'Katalog',
    fullList: "To'liq ro'yxat",
    partnersTitle: 'Hamkorlar',

    b2bOffer: 'Katta hajmdagi B2B xaridlar uchun maxsus taklif',
    b2bDesc: '"Original Grand Plast" dilerlar, fermerlar va eksportyorlar uchun qulay shartlarda hamkorlikni taklif qiladi.',
    requestOffer: "Kommersiya taklifini so'rash",
    headOffice: 'Bosh ofis',
    b2bBenefit1: 'Individual narx va uzoq muddatli kontrakt',
    b2bBenefit2: 'Eksport hujjatlari va logistika yordami',
    b2bBenefit3: '24/7 shaxsiy menejer va tez aloqa',
    b2bBenefit4: 'Kafolatlangan sifat va barqaror yetkazib berish',

    agroDesc: "100-200 mikron oralig'idagi ko'p qatlamli UV, IR va EVA qo'shimchali plyonkalar ishlab chiqaramiz.",
    agroSpecWidthLabel: 'Maksimal kenglik',
    agroSpecWidthValue: '12 metrgacha',
    agroSpecUvLabel: 'UV kafolat',
    agroSpecUvValue: '3-5 yil',
    agroSpecLightLabel: "Yorug'lik o'tkazuvchanlik",
    agroSpecLightValue: '88-92%',
    thermoDesc: "Guruhli va palletli qadoqlash uchun mo'ljallangan texnik plyonkalar.",
    thermoSpecStretchLabel: "Uzilishdagi cho'zilish",
    thermoSpecStretchValue: '>= 350% MD',
    thermoSpecShrinkLabel: 'Termik siqilish',
    thermoSpecShrinkValue: 'T 50-70% / K 30-50%',
    thermoSpecDensityLabel: 'Zichlik',
    thermoSpecDensityValue: '0.925 g/cm3',
    logisticsDesc: "Og'ir yuklar uchun xavfsiz va mustahkam ekstrudirovka qilingan polimer materiallar.",
    logisticsSpecSeamLabel: 'Payvand choki',
    logisticsSpecSeamValue: 'Plexus texnologiyasi',
    logisticsSpecLoadLabel: 'Chidamli yuk',
    logisticsSpecLoadValue: '35 kggacha',
    logisticsSpecIndustryLabel: 'Soha',
    logisticsSpecIndustryValue: 'B2B eksport',

    categoryGreenhouseFilm: 'Issiqxona plyonkasi',
    categoryShrinkFilm: 'Termo-usadoz plyonka',
    categoryPolyethyleneBags: 'Polietilen paketlar',
    categoryPetCapsules: 'PET kapsulalar',
    categoryRoofingMaterials: 'Tom yopish materiallari',
    categoryBitumenMastic: 'Bitum-polimer mastika',
    categoryPlainFilm: 'Oddiy plyonka',
    categoryUvFilm: 'UV himoyali',
    categoryMultiLayerFilm: "Ko'p qavatli",
    categorySpecialFilm: 'Maxsus plyonka',
    categoryOther: 'Boshqa',

    productInfo: "MAHSULOT HAQIDA",
    allProducts: 'Barcha mahsulotlar',
    price: 'Narx',
    inStock: 'Mavjud',
    outOfStock: "Mavjud emas",
    addToCart: "Savatga qo'shish",
    addedToCart: "Savatga qo'shildi!",
    cartTitle: 'Savatcha',
    som: "so'm",
    thickness: 'Qalinlik',
    width: 'Eni',
    length: 'Uzunlik',
    quantity: 'Miqdor',
    total: 'Jami',
    checkout: 'Buyurtma berish',
    removeItem: "O'chirish",
    orderSuccess: 'Buyurtma qabul qilindi!',
    orderSuccessDesc: 'Sizning buyurtmangiz muvaffaqiyatli qabul qilindi. Profilingizda buyurtma holatini kuzatishingiz mumkin.',
    goToProfile: "Profilga o'tish",
    continueShopping: 'Xaridni davom ettirish',
    emptyCart: "Savat bo'sh",
    emptyCartDesc: "Mahsulotlarni ko'rib, savatga qo'shing",
    viewProducts: "Mahsulotlarni ko'rish",
    cartItemCount: 'ta mahsulot',
    orderSummary: 'Buyurtma xulosasi',
    promoCode: 'Promokod',
    promoApplied: "qo'llanildi",
    productsLabel: 'Mahsulotlar',
    discount: 'Chegirma',
    shippingAddress: 'Yetkazish manzili',
    fullAddress: "To'liq manzil",
    phoneNumber: 'Telefon raqam',
    note: 'Izoh',
    additionalNote: "Qo'shimcha izoh...",
    sending: 'Yuborilmoqda...',
    loginAndOrder: 'Kirish va buyurtma berish',
    addressPhoneRequired: 'Manzil va telefon raqam kiritilishi shart',
    ctaTitle: "Katta hajmli buyurtmalar uchun ishlab chiqaruvchidan to'g'ridan-to'g'ri",
    ctaDesc: 'Individual narxlar, barqaror yetkazib berish, eksport hujjatlari va logistika yordami — hammasi bir joyda.',
    footerPhone: 'Telefon',
    footerEmail: 'Email',
    footerAddress: 'Manzil',
    footerAddressValue: "Toshkent, O'zbekiston",
    uvProtection: 'UV himoya',
    viewImage: "Rasmni ko'rish",

    heroSlide1Title: 'Agro-Plyonkalar bilan yuqori hosil',
    heroSlide1Subtitle: 'Issiqxonalaringiz uchun maxsus ishlab chiqilgan, UV-nurlari va murakkab ob-havodan himoya qiluvchi premium plyonkalar.',
    heroSlide2Title: 'Sanoat Termo Qadoqlash',
    heroSlide2Subtitle: "Logistika jarayonida mahsulotlaringiz xavfsizligini 100% taminlang. Mustahkam va cho'ziluvchan termo plyonkalar.",
    heroSlide3Title: 'Qurilish va Gidroizolyatsiya',
    heroSlide3Subtitle: "Kuchli va qalin qoplamalar bilan poydevor va tomlarni namlikdan mukammal asrang. Biz bilan inshootlaringiz uzoq umr ko'radi.",
    heroSlide4Title: 'Ishonchli va Ekologik toza',
    heroSlide4Subtitle: 'Oziq-ovqat sanoati uchun mutlaqo xavfsiz innovatsion qadoqlash plyonkalari. Mahsulot yangiligini uzoq muddat saqlaydi.',
    heroSlide5Title: 'Hamkorlik va Barqarorlik',
    heroSlide5Subtitle: "O'zbekiston bo'ylab distribyutorlar tarmog'iga qo'shiling. Sifatli plyonka — muvaffaqiyatli savdo garovi.",

    allNews: 'Barcha yangiliklar',
    feature: 'Yangilik',
    pressRelease: 'Press-reliz',
    announcement: "E'lon",
    article: 'Maqola',
    latestNews: "So'nggi yangiliklar",
    newsSubtitle: "Korxona yangiliklari va e'lonlari",
    readMore: "Batafsil o'qish",
    backToNews: 'Yangiliklarga qaytish',

    contactTitle: "Biz bilan bog'laning",
    contactSubtitle: "Savollaringiz bo'lsa yoki buyurtma bermoqchi bo'lsangiz, murojaat qiling",
    address: 'Manzil',
    addressValue: "Toshkent sh., Uchtepa tumani, Foziltepa ko'chasi, 9-uy",
    phone: 'Telefon',
    email: 'Email',
    website: 'Veb-sayt',
    workHours: 'Ish vaqti',
    workHoursValue: 'Du-Ju: 08:00 - 18:00',
    sendMessage: 'Xabar yuborish',
    yourName: 'Ismingiz',
    yourEmail: 'Email manzilingiz',
    yourPhone: 'Telefon raqamingiz',
    message: 'Xabaringiz',
    send: 'Yuborish',

    loginTitle: 'Tizimga kirish',
    loginSubtitle: 'Hisobingizga kiring va xarid qiling',
    emailPlaceholder: 'email@misol.uz',
    password: 'Parol',
    passwordPlaceholder: 'Parolingiz',
    loggingIn: 'Kirilmoqda...',
    noAccount: "Hisobingiz yo'qmi?",
    registerTitle: "Ro'yxatdan o'tish",
    registerSubtitle: 'Yangi hisob yarating',
    name: 'Ism',
    phonePlaceholder: '+998 90 123 45 67',
    haveAccount: 'Hisobingiz bormi?',
    fullNamePlaceholder: "To'liq ismingiz",
    phoneLabel: 'Telefon raqam',
    confirmPassword: 'Parolni tasdiqlash',
    confirmPasswordPlaceholder: 'Parolni qayta kiriting',
    minPasswordPlaceholder: 'Kamida 6 belgi',
    registerLoading: "Ro'yxatdan o'tilmoqda...",
    signIn: 'Kirish',
    passwordMismatch: 'Parollar mos kelmaydi',
    passwordMinLength: "Parol kamida 6 belgidan iborat bo'lishi kerak",

    footerDesc: "O'zbekistonda polietilen plyonka va qadoqlash materiallari ishlab chiqaruvchi yetakchi korxona.",
    quickLinks: 'Tezkor havolalar',
    contactInfo: "Aloqa ma'lumotlari",
    allRightsReserved: 'Barcha huquqlar himoyalangan.',
    followUs: 'Ijtimoiy tarmoqlar',
    socialTelegram: 'Telegram',
    socialInstagram: 'Instagram',
    socialFacebook: 'Facebook',
    socialLinkedin: 'LinkedIn',

    statusPending: 'Kutilmoqda',
    statusAccepted: 'Qabul qilindi',
    statusPreparing: 'Tayyorlanmoqda',
    statusDelivered: 'Yetkazildi',
    statusRollbackError: "Statusni avvalgi bosqichga qaytarib bo'lmaydi",

    adminDashboard: 'Dashboard',
    adminProducts: 'Mahsulotlar',
    adminNews: 'Yangiliklar',
    adminOrders: 'Buyurtmalar',
    adminUsers: 'Foydalanuvchilar',
    adminPromo: 'Promokodlar',
    backToSite: 'Saytga qaytish',
    allStatuses: 'Barcha statuslar',
    orderNumber: 'Raqam',
    customer: 'Mijoz',
    orderDate: 'Sana',
    changeStatus: "O'zgartirish",
    noOrders: "Buyurtmalar yo'q",
    unknownUser: "Noma'lum",
    productsInOrder: 'Mahsulotlar',
    amount: 'Jami',
    status: 'Status',
    dashboardTitle: 'Dashboard',
    analyticsTitle: 'Analitika',
    dataLoadError: "Ma'lumot yuklanmadi",
    totalOrdersLabel: 'Jami buyurtmalar',
    deliveredOrdersLabel: 'Sotuvlar (yetkazildi)',
    totalRevenueLabel: "Jami daromad (so'm)",
    totalUsersLabel: 'Jami foydalanuvchilar',
    newUsersLabel: 'Yangi foydalanuvchilar',
    totalProductsLabel: 'Jami mahsulotlar',
    newProductsLabel: 'Yangi mahsulotlar',
    diffShortLabel: 'farq',
    avgOrderLabel: "O'rtacha buyurtma (so'm)",
    avgOrderValueLabel: "O'rtacha buyurtma qiymati",
    monthlyRevenueOrdersChart: 'Oylik daromad va buyurtmalar',
    dailyRevenueChart: 'Kunlik daromad (30 kun)',
    dailyOrdersChart: 'Kunlik buyurtmalar (30 kun)',
    orderStatusesChart: 'Buyurtma statuslari',
    orderStatusesDistributionChart: 'Buyurtma statuslari taqsimoti',
    recentOrdersLabel: "So'nggi buyurtmalar",
    revenueLabel: "Daromad (so'm)",
    ordersLabel: 'Buyurtmalar',
    dailyRevenueLabel: 'Kunlik daromad',
    dailyOrdersCountLabel: 'Buyurtmalar soni',
    selectPeriod: 'Muddatlarni tanlang',
    period1: 'Muddat 1',
    period2: 'Muddat 2',
    dateFrom: 'Dan',
    dateTo: 'Gacha',
    compareLabel: 'Taqqoslash',
    compareDateFrom: 'Taqqoslash dan',
    compareDateTo: 'Gacha',
    applyFilter: "Qo'llash",
    resetFilter: 'Tozalash',
    totalCostLabel: "Tan narx xarajati (so'm)",
    realProfitLabel: "Haqiqiy foyda (so'm)",
    profitMarginLabel: 'Foyda foizi',
    costLabel: 'Tan narx',
    profitLabel: 'Foyda',
    comparisonTitle: 'Davrlar taqqoslash',
    comparisonMetric: "Ko'rsatkich",
    changeLabel: "O'zgarish",
    prevPeriodOrders: 'Oldingi davr buyurtmalar',
    prevPeriodRevenue: 'Oldingi davr daromad',
    prevPeriodCost: 'Oldingi davr tan narx',
    prevPeriodProfit: 'Oldingi davr foyda',
    monthlyRevenueCostProfitChart: 'Oylik daromad, tan narx va foyda',
    dailyRevenueCostChart: 'Kunlik daromad, tan narx va foyda',
    footerBrandSubtitle: 'Premium polimer yechimlar',
    aboutHeroBadge: '2005 yildan beri faoliyat yuritmoqda',
    aboutHeroDesc: "2005-yildan buyon polietilen va polimer materiallari ishlab chiqaruvchi Markaziy Osiyodagi yetakchi korxona. O'zbekistonda birinchi bo'lib 12 metrli uch qatlamli plyonkani taqdim etgan innovatsion zavod.",
    aboutHistoryBadge: 'Tarix',
    aboutHistoryTitle: 'Korxona haqida',
    aboutStoryP1: "Original Grand Plast MChJ 2005 yilda Toshkent shahrida tashkil topgan bo'lib, asosiy faoliyat yo'nalishi polietilen plyonka va qadoqlash materiallari ishlab chiqarishdir. Korxona ilk yillarida turli xil polietilen mahsulotlar ishlab chiqarishga ixtisoslashdi.",
    aboutStoryP2: "2013-yilda korxonamiz O'zbekiston sanoatida yangi bosqichni boshlab berdi - mamlakatimizda birinchi marotaba uch qatlamli, kengligi 12 metrga yetuvchi issiqxona plyonkalarini ishlab chiqarishni yo'lga qo'ydi. Bu texnologiya agrar sektorga yirik hajmdagi issiqxonalarni choklarsiz va mustahkam qoplash imkonini berdi.",
    aboutStoryP3: "Bizning muvaffaqiyatimiz zamonaviy texnologiyalarga asoslangan. Ishlab chiqarish liniyalarimiz Ispaniya, Koreya, Xitoy va Turkiyaning ilg'or uskunalari bilan jihozlangan. Xom-ashyo sifatida Repsol, Lotte Chemical va Sinopec mahsulotlaridan foydalanamiz.",
    aboutStoryP4: "Bundan tashqari, biz gidroizolyatsiya sohasida ham o'z o'rnimizga egamiz. ROOF COVER brendi ostida ishlab chiqarilayotgan rulonli tom yopish materiallari va bitum-polimer mastikalari qurilish bozorida yuqori sifat standarti hisoblanadi.",
    aboutMilestone1Title: 'Tashkil etilish',
    aboutMilestone1Desc: "Toshkentda polietilen mahsulotlari ishlab chiqarishga asos solindi.",
    aboutMilestone2Title: '12 metrlik rekord',
    aboutMilestone2Desc: "O'zbekistonda ilk bor 3 qatlamli, 12 metrli issiqxona plyonkasi ishlab chiqarish yo'lga qo'yildi.",
    aboutMilestone3Label: 'Global',
    aboutMilestone3Title: 'Xalqaro hamkorlik',
    aboutMilestone3Desc: "Repsol, Lotte va Sinopec kabi xalqaro yetkazib beruvchilar bilan barqaror hamkorlik yo'lga qo'yildi.",
    aboutSummaryMeta: '2005 yildan beri | Toshkent',
    aboutSummaryBadge: "O'zbekistonda No.1 issiqxona plyonkasi",
    aboutActivitiesBadge: 'Faoliyat',
    aboutActivitiesTitle: "Asosiy yo'nalishlar",
    aboutActivity1Title: 'Issiqxona plyonkasi',
    aboutActivity1Desc: "Kuchli UV nurlanishga chidamli, uch qatlamli polietilen plyonka. 12 metr gacha kenglik.",
    aboutActivity2Title: 'Termo-usadoz plyonka',
    aboutActivity2Desc: "Issiq bilan ishlov berilganda tavlanib, mahsulotlarni mustahkam o'rashda qo'llaniladi.",
    aboutActivity3Title: 'Polietilen paketlar',
    aboutActivity3Desc: "Banklar uchun pulni vakuum bilan o'rash sumkalari va turli hajmdagi paketlar.",
    aboutActivity4Title: 'PET kapsulalar',
    aboutActivity4Desc: "Suv va yog' idishlari uchun 28-140 gramm oralig'idagi qopqoq materiallari.",
    aboutActivity5Title: 'Gidroizolyatsiya',
    aboutActivity5Desc: "Rulonli tom yopish va gidroizolyatsiya materiallari. Issiq va sovuqqa chidamli, uzoq xizmat qiluvchi qoplamalar.",
    aboutActivity6Title: 'Bitum-polimer mastika',
    aboutActivity6Desc: 'Gidroizolyatsiya va germetizatsiya ishlari uchun yuqori adgeziyali polimer mastikalar.',
    aboutValuesBadge: 'Qadriyatlar',
    aboutValuesTitle: 'Missiya va maqsad',
    aboutValue1Title: 'Missiyamiz',
    aboutValue1Desc: 'Zamonaviy texnologiyalar va sifatli xomashyodan foydalanib, mijozlarga foydali va arzon qadoqlash yechimlarini taqdim etish.',
    aboutValue2Title: 'Qadriyatlarimiz',
    aboutValue2Desc: 'Sifat, ishonchlilik va innovatsiya. Har bir hamkor bilan uzoq muddatli hamkorlikni saqlashga intilamiz.',
    aboutValue3Title: 'Ekologiya',
    aboutValue3Desc: "Chiqindilarni kamaytirish va qayta ishlash imkoniyatlariga alohida e'tibor qaratamiz.",
    aboutValue4Title: 'Individual yondashuv',
    aboutValue4Desc: 'Har bir mijoz bilan alohida ishlaymiz. Katta partiyalar uchun maxsus narx shartlarini taklif qilamiz.',
    aboutContactBadge: 'Aloqa',
    aboutContactTitle: "Biz bilan bog'laning",
    aboutContactSubtitle: "Savollaringiz bo'lsa yoki buyurtma bermoqchi bo'lsangiz - murojaat qiling.",
    aboutMapTitle: 'Original Grand Plast manzili',
    aboutContactAddressLabel: 'Manzil',
    aboutContactAddressValue: "Toshkent sh., Uchtepa tumani, Foziltepa ko'chasi, 9-uy",
    aboutContactPhone1Label: 'Telefon',
    aboutContactPhone2Label: 'Telefon 2',
    aboutContactPhone3Label: 'Telefon 3',
    aboutContactEmailLabel: 'Email',
    aboutContactWebsiteLabel: 'Veb-sayt',
    aboutContactHoursLabel: 'Ish vaqti',
    aboutContactHoursValue: 'Du-Ju: 08:00 - 18:00',
    aboutCtaTitle: 'Hamkorlik qilishga tayyormisiz?',
    aboutCtaDesc: "Mahsulotlar, narxlar va yetkazib berish haqida batafsil ma'lumot uchun qo'ng'iroq qiling.",
    aboutCtaButton: "Qo'ng'iroq qilish",
  },
  ru: {
    home: 'Главная',
    about: 'О нас',
    products: 'Продукция',
    news: 'Новости',
    promotions: 'Акции',
    contacts: 'Контакты',
    login: 'Войти',
    register: 'Регистрация',
    cart: 'Корзина',
    profile: 'Профиль',
    search: 'Поиск...',
    adminPanel: 'Админ панель',
    logout: 'Выйти',

    heroTitle1: 'Для промышленности и агросектора',
    heroTitle2: 'инновационные полимерные',
    heroTitle3: 'решения',
    heroSubtitle: 'С 2005 года производим качественные полимерные материалы для рынка Центральной Азии.',

    techSolutions: 'Технологические решения',
    techDesc: 'Полимерные материалы с высокими физико-механическими показателями по международным стандартам.',
    agroTitle: 'Агропромышленные комплексы',
    thermoTitle: 'Термоусадочная упаковка (Shrink)',
    logisticsTitle: 'Промышленные логистические пакеты',
    moreParams: 'Подробнее',
    onlineCatalog: 'Каталог',
    fullList: 'Полный список',
    partnersTitle: 'Партнеры',

    b2bOffer: 'Специальное предложение для крупных B2B закупок',
    b2bDesc: '"Original Grand Plast" предлагает выгодные условия для дилеров, фермеров и экспортёров.',
    requestOffer: 'Запросить коммерческое предложение',
    headOffice: 'Головной офис',
    b2bBenefit1: 'Индивидуальные цены и долгосрочный контракт',
    b2bBenefit2: 'Экспортные документы и логистическая поддержка',
    b2bBenefit3: 'Персональный менеджер 24/7',
    b2bBenefit4: 'Гарантированное качество и стабильные поставки',

    agroDesc: 'Производим многослойные пленки 100-200 микрон с добавками UV, IR и EVA.',
    agroSpecWidthLabel: 'Максимальная ширина',
    agroSpecWidthValue: 'до 12 метров',
    agroSpecUvLabel: 'UV гарантия',
    agroSpecUvValue: '3-5 лет',
    agroSpecLightLabel: 'Светопропускание',
    agroSpecLightValue: '88-92%',
    thermoDesc: 'Технические пленки для групповой и паллетной упаковки на автоматических линиях.',
    thermoSpecStretchLabel: 'Удлинение при разрыве',
    thermoSpecStretchValue: '>= 350% MD',
    thermoSpecShrinkLabel: 'Термоусадка',
    thermoSpecShrinkValue: 'T 50-70% / K 30-50%',
    thermoSpecDensityLabel: 'Плотность',
    thermoSpecDensityValue: '0.925 g/cm3',
    logisticsDesc: 'Экструдированные полимерные материалы для тяжелой логистики.',
    logisticsSpecSeamLabel: 'Сварной шов',
    logisticsSpecSeamValue: 'Технология Plexus',
    logisticsSpecLoadLabel: 'Нагрузка',
    logisticsSpecLoadValue: 'до 35 кг',
    logisticsSpecIndustryLabel: 'Сегмент',
    logisticsSpecIndustryValue: 'B2B экспорт',

    categoryGreenhouseFilm: 'Тепличная пленка',
    categoryShrinkFilm: 'Термоусадочная пленка',
    categoryPolyethyleneBags: 'Полиэтиленовые пакеты',
    categoryPetCapsules: 'ПЭТ капсулы',
    categoryRoofingMaterials: 'Кровельные материалы',
    categoryBitumenMastic: 'Битумно-полимерная мастика',
    categoryPlainFilm: 'Обычная пленка',
    categoryUvFilm: 'С UV защитой',
    categoryMultiLayerFilm: 'Многослойная',
    categorySpecialFilm: 'Специальная пленка',
    categoryOther: 'Другое',

    productInfo: 'О ПРОДУКТЕ',
    allProducts: 'Все продукты',
    price: 'Цена',
    inStock: 'В наличии',
    outOfStock: 'Нет в наличии',
    addToCart: 'В корзину',
    addedToCart: 'Добавлено в корзину!',
    cartTitle: 'Корзина',
    som: 'сум',
    thickness: 'Толщина',
    width: 'Ширина',
    length: 'Длина',
    quantity: 'Количество',
    total: 'Итого',
    checkout: 'Оформить заказ',
    removeItem: 'Удалить',
    orderSuccess: 'Заказ принят!',
    orderSuccessDesc: 'Ваш заказ успешно принят. Вы можете отслеживать статус заказа в профиле.',
    goToProfile: 'Перейти в профиль',
    continueShopping: 'Продолжить покупки',
    emptyCart: 'Корзина пуста',
    emptyCartDesc: 'Просмотрите товары и добавьте в корзину',
    viewProducts: 'Смотреть товары',
    cartItemCount: 'товаров',
    orderSummary: 'Итоги заказа',
    promoCode: 'Промокод',
    promoApplied: 'применен',
    productsLabel: 'Товары',
    discount: 'Скидка',
    shippingAddress: 'Адрес доставки',
    fullAddress: 'Полный адрес',
    phoneNumber: 'Номер телефона',
    note: 'Примечание',
    additionalNote: 'Дополнительное примечание...',
    sending: 'Отправка...',
    loginAndOrder: 'Войти и оформить',
    addressPhoneRequired: 'Необходимо указать адрес и телефон',
    ctaTitle: 'Прямые поставки от производителя для крупных заказов',
    ctaDesc: 'Индивидуальные цены, стабильные поставки, экспортная документация и логистическая поддержка — всё в одном месте.',
    footerPhone: 'Телефон',
    footerEmail: 'Email',
    footerAddress: 'Адрес',
    footerAddressValue: 'Ташкент, Узбекистан',
    uvProtection: 'UV защита',
    viewImage: 'Посмотреть фото',

    heroSlide1Title: 'Высокий урожай с Агро-Плёнками',
    heroSlide1Subtitle: 'Премиальные плёнки, специально разработанные для теплиц, защищающие от UV-лучей и сложных погодных условий.',
    heroSlide2Title: 'Промышленная Термоупаковка',
    heroSlide2Subtitle: 'Обеспечьте 100% сохранность вашей продукции при логистике. Прочные и эластичные термоусадочные плёнки.',
    heroSlide3Title: 'Строительство и Гидроизоляция',
    heroSlide3Subtitle: 'Надёжно защитите фундаменты и кровли от влаги прочными и толстыми покрытиями. С нами ваши строения прослужат долго.',
    heroSlide4Title: 'Надёжно и Экологично',
    heroSlide4Subtitle: 'Инновационные упаковочные плёнки, абсолютно безопасные для пищевой промышленности. Сохраняют свежесть продуктов надолго.',
    heroSlide5Title: 'Партнёрство и Стабильность',
    heroSlide5Subtitle: 'Присоединяйтесь к дистрибьюторской сети по всему Узбекистану. Качественная плёнка — залог успешной торговли.',

    allNews: 'Все новости',
    feature: 'Новость',
    pressRelease: 'Пресс-релиз',
    announcement: 'Объявление',
    article: 'Статья',
    latestNews: 'Последние новости',
    newsSubtitle: 'Новости и объявления компании',
    readMore: 'Подробнее',
    backToNews: 'Назад к новостям',

    contactTitle: 'Свяжитесь с нами',
    contactSubtitle: 'Если у вас есть вопросы или вы хотите оформить заказ, свяжитесь с нами',
    address: 'Адрес',
    addressValue: 'г. Ташкент, Учтепинский район, ул. Фозилтепа, дом 9',
    phone: 'Телефон',
    email: 'Email',
    website: 'Веб-сайт',
    workHours: 'Режим работы',
    workHoursValue: 'Пн-Пт: 08:00 - 18:00',
    sendMessage: 'Отправить сообщение',
    yourName: 'Ваше имя',
    yourEmail: 'Ваш email',
    yourPhone: 'Ваш телефон',
    message: 'Сообщение',
    send: 'Отправить',

    loginTitle: 'Вход',
    loginSubtitle: 'Войдите в аккаунт для покупок',
    emailPlaceholder: 'email@example.com',
    password: 'Пароль',
    passwordPlaceholder: 'Ваш пароль',
    loggingIn: 'Вход...',
    noAccount: 'Нет аккаунта?',
    registerTitle: 'Регистрация',
    registerSubtitle: 'Создайте новый аккаунт',
    name: 'Имя',
    phonePlaceholder: '+998 90 123 45 67',
    haveAccount: 'Уже есть аккаунт?',
    fullNamePlaceholder: 'Ваше полное имя',
    phoneLabel: 'Номер телефона',
    confirmPassword: 'Подтвердите пароль',
    confirmPasswordPlaceholder: 'Повторите пароль',
    minPasswordPlaceholder: 'Минимум 6 символов',
    registerLoading: 'Регистрация...',
    signIn: 'Войти',
    passwordMismatch: 'Пароли не совпадают',
    passwordMinLength: 'Пароль должен содержать минимум 6 символов',

    footerDesc: 'Ведущее предприятие по производству полиэтиленовой пленки и упаковочных материалов в Узбекистане.',
    quickLinks: 'Быстрые ссылки',
    contactInfo: 'Контактная информация',
    allRightsReserved: 'Все права защищены.',
    followUs: 'Социальные сети',
    socialTelegram: 'Telegram',
    socialInstagram: 'Instagram',
    socialFacebook: 'Facebook',
    socialLinkedin: 'LinkedIn',

    statusPending: 'Ожидается',
    statusAccepted: 'Принят',
    statusPreparing: 'Готовится',
    statusDelivered: 'Доставлен',
    statusRollbackError: 'Нельзя вернуть заказ на предыдущий статус',

    adminDashboard: 'Дашборд',
    adminProducts: 'Продукты',
    adminNews: 'Новости',
    adminOrders: 'Заказы',
    adminUsers: 'Пользователи',
    adminPromo: 'Промокоды',
    backToSite: 'Вернуться на сайт',
    allStatuses: 'Все статусы',
    orderNumber: 'Номер',
    customer: 'Клиент',
    orderDate: 'Дата',
    changeStatus: 'Изменение',
    noOrders: 'Заказов нет',
    unknownUser: 'Неизвестно',
    productsInOrder: 'Товары',
    amount: 'Сумма',
    status: 'Статус',
    dashboardTitle: 'Дашборд',
    analyticsTitle: 'Аналитика',
    dataLoadError: 'Не удалось загрузить данные',
    totalOrdersLabel: 'Всего заказов',
    deliveredOrdersLabel: 'Продажи (доставлено)',
    totalRevenueLabel: 'Общая выручка (сум)',
    totalUsersLabel: 'Всего пользователей',
    newUsersLabel: 'Новые пользователи',
    totalProductsLabel: 'Всего товаров',
    newProductsLabel: 'Новые товары',
    diffShortLabel: 'разница',
    avgOrderLabel: 'Средний заказ (сум)',
    avgOrderValueLabel: 'Средний чек',
    monthlyRevenueOrdersChart: 'Месячная выручка и заказы',
    dailyRevenueChart: 'Дневная выручка (30 дней)',
    dailyOrdersChart: 'Дневные заказы (30 дней)',
    orderStatusesChart: 'Статусы заказов',
    orderStatusesDistributionChart: 'Распределение статусов заказов',
    recentOrdersLabel: 'Последние заказы',
    revenueLabel: 'Выручка (сум)',
    ordersLabel: 'Заказы',
    dailyRevenueLabel: 'Дневная выручка',
    dailyOrdersCountLabel: 'Количество заказов',
    selectPeriod: 'Выберите период',
    period1: 'Период 1',
    period2: 'Период 2',
    dateFrom: 'С',
    dateTo: 'По',
    compareLabel: 'Сравнить',
    compareDateFrom: 'Сравнить с',
    compareDateTo: 'По',
    applyFilter: 'Применить',
    resetFilter: 'Сбросить',
    totalCostLabel: 'Себестоимость (сум)',
    realProfitLabel: 'Реальная прибыль (сум)',
    profitMarginLabel: 'Маржа прибыли',
    costLabel: 'Себестоимость',
    profitLabel: 'Прибыль',
    comparisonTitle: 'Сравнение периодов',
    comparisonMetric: 'Показатель',
    changeLabel: 'Изменение',
    prevPeriodOrders: 'Заказы предыдущего периода',
    prevPeriodRevenue: 'Выручка предыдущего периода',
    prevPeriodCost: 'Себестоимость предыдущего периода',
    prevPeriodProfit: 'Прибыль предыдущего периода',
    monthlyRevenueCostProfitChart: 'Месячная выручка, себестоимость и прибыль',
    dailyRevenueCostChart: 'Дневная выручка, себестоимость и прибыль',
    footerBrandSubtitle: 'Премиальные полимерные решения',
    aboutHeroBadge: 'Работает с 2005 года',
    aboutHeroDesc: 'С 2005 года компания является одним из ведущих производителей полиэтилена и полимерных материалов в Центральной Азии. Инновационный завод первым в Узбекистане запустил выпуск трехслойной пленки шириной 12 метров.',
    aboutHistoryBadge: 'История',
    aboutHistoryTitle: 'О компании',
    aboutStoryP1: 'Original Grand Plast MChJ основана в 2005 году в Ташкенте. Основное направление деятельности - производство полиэтиленовой пленки и упаковочных материалов. В первые годы компания специализировалась на выпуске различных полиэтиленовых изделий.',
    aboutStoryP2: 'В 2013 году предприятие вывело отрасль на новый уровень - впервые в Узбекистане было запущено производство трехслойной тепличной пленки шириной до 12 метров. Эта технология позволила покрывать крупные теплицы без швов и с высокой прочностью.',
    aboutStoryP3: 'Наш успех основан на современных технологиях. Производственные линии оснащены передовым оборудованием из Испании, Кореи, Китая и Турции. В качестве сырья мы используем материалы Repsol, Lotte Chemical и Sinopec.',
    aboutStoryP4: 'Кроме того, мы уверенно развиваем направление гидроизоляции. Рулонные кровельные материалы и битумно-полимерные мастики под брендом ROOF COVER считаются стандартом качества на строительном рынке.',
    aboutMilestone1Title: 'Основание компании',
    aboutMilestone1Desc: 'В Ташкенте запущено производство полиэтиленовой продукции.',
    aboutMilestone2Title: 'Рекорд 12 метров',
    aboutMilestone2Desc: 'Впервые в Узбекистане запущено производство трехслойной тепличной пленки шириной 12 метров.',
    aboutMilestone3Label: 'Global',
    aboutMilestone3Title: 'Международное партнерство',
    aboutMilestone3Desc: 'Налажено стабильное сотрудничество с международными поставщиками, включая Repsol, Lotte и Sinopec.',
    aboutSummaryMeta: 'С 2005 года | Ташкент',
    aboutSummaryBadge: 'Тепличная пленка No.1 в Узбекистане',
    aboutActivitiesBadge: 'Направления',
    aboutActivitiesTitle: 'Ключевые направления',
    aboutActivity1Title: 'Тепличная пленка',
    aboutActivity1Desc: 'Трехслойная полиэтиленовая пленка, устойчивая к интенсивному UV-излучению. Ширина до 12 метров.',
    aboutActivity2Title: 'Термоусадочная пленка',
    aboutActivity2Desc: 'Используется для прочной упаковки продукции после термической обработки.',
    aboutActivity3Title: 'Полиэтиленовые пакеты',
    aboutActivity3Desc: 'Вакуумные пакеты для банков и пакеты различных размеров для повседневного использования.',
    aboutActivity4Title: 'PET-капсулы',
    aboutActivity4Desc: 'Материалы для крышек бутылок воды и масла весом от 28 до 140 граммов.',
    aboutActivity5Title: 'Гидроизоляция',
    aboutActivity5Desc: 'Рулонные кровельные и гидроизоляционные материалы, устойчивые к жаре и холоду и рассчитанные на долгий срок службы.',
    aboutActivity6Title: 'Битумно-полимерная мастика',
    aboutActivity6Desc: 'Полимерные мастики с высокой адгезией для гидроизоляции и герметизации.',
    aboutValuesBadge: 'Ценности',
    aboutValuesTitle: 'Миссия и цели',
    aboutValue1Title: 'Наша миссия',
    aboutValue1Desc: 'Предлагать клиентам полезные и доступные упаковочные решения, используя современные технологии и качественное сырье.',
    aboutValue2Title: 'Наши ценности',
    aboutValue2Desc: 'Качество, надежность и инновации. Мы стремимся к долгосрочному сотрудничеству с каждым партнером.',
    aboutValue3Title: 'Экология',
    aboutValue3Desc: 'Особое внимание уделяем снижению отходов и возможностям переработки.',
    aboutValue4Title: 'Индивидуальный подход',
    aboutValue4Desc: 'Работаем с каждым клиентом отдельно и предлагаем специальные ценовые условия для крупных партий.',
    aboutContactBadge: 'Контакты',
    aboutContactTitle: 'Свяжитесь с нами',
    aboutContactSubtitle: 'Если у вас есть вопросы или вы хотите оформить заказ - свяжитесь с нами.',
    aboutMapTitle: 'Адрес Original Grand Plast',
    aboutContactAddressLabel: 'Адрес',
    aboutContactAddressValue: 'г. Ташкент, Учтепинский район, ул. Фозилтепа, дом 9',
    aboutContactPhone1Label: 'Телефон',
    aboutContactPhone2Label: 'Телефон 2',
    aboutContactPhone3Label: 'Телефон 3',
    aboutContactEmailLabel: 'Email',
    aboutContactWebsiteLabel: 'Веб-сайт',
    aboutContactHoursLabel: 'Часы работы',
    aboutContactHoursValue: 'Пн-Пт: 08:00 - 18:00',
    aboutCtaTitle: 'Готовы к сотрудничеству?',
    aboutCtaDesc: 'Позвоните нам, чтобы получить подробную информацию о продукции, ценах и доставке.',
    aboutCtaButton: 'Позвонить',
  },
  en: {
    home: 'Home',
    about: 'About',
    products: 'Products',
    news: 'News',
    promotions: 'Promotions',
    contacts: 'Contacts',
    login: 'Login',
    register: 'Register',
    cart: 'Cart',
    profile: 'Profile',
    search: 'Search...',
    adminPanel: 'Admin Panel',
    logout: 'Logout',

    heroTitle1: 'For industry and agriculture',
    heroTitle2: 'innovative polymer',
    heroTitle3: 'solutions',
    heroSubtitle: 'Since 2005, we have produced high-quality polymer materials for the Central Asian market.',

    techSolutions: 'Technological solutions',
    techDesc: 'Polymer materials with high physical and mechanical performance, aligned with global standards.',
    agroTitle: 'Agro-industrial complexes',
    thermoTitle: 'Shrink packaging',
    logisticsTitle: 'Industrial logistics packaging',
    moreParams: 'More details',
    onlineCatalog: 'Catalog',
    fullList: 'Full list',
    partnersTitle: 'Partners',

    b2bOffer: 'Special offer for large B2B purchases',
    b2bDesc: '"Original Grand Plast" offers favorable terms for dealers, farms, and exporters.',
    requestOffer: 'Request commercial offer',
    headOffice: 'Head office',
    b2bBenefit1: 'Individual pricing and long-term contracts',
    b2bBenefit2: 'Export documentation and logistics support',
    b2bBenefit3: 'Dedicated 24/7 account manager',
    b2bBenefit4: 'Guaranteed quality and stable supply',

    agroDesc: 'We produce 100-200 micron multilayer films with UV, IR, and EVA additives.',
    agroSpecWidthLabel: 'Maximum width',
    agroSpecWidthValue: 'up to 12 meters',
    agroSpecUvLabel: 'UV warranty',
    agroSpecUvValue: '3-5 years',
    agroSpecLightLabel: 'Light transmission',
    agroSpecLightValue: '88-92%',
    thermoDesc: 'Technical films for grouped and pallet packaging on automated lines.',
    thermoSpecStretchLabel: 'Elongation at break',
    thermoSpecStretchValue: '>= 350% MD',
    thermoSpecShrinkLabel: 'Thermal shrinkage',
    thermoSpecShrinkValue: 'T 50-70% / K 30-50%',
    thermoSpecDensityLabel: 'Density',
    thermoSpecDensityValue: '0.925 g/cm3',
    logisticsDesc: 'Extruded polymer materials for heavy-duty logistics.',
    logisticsSpecSeamLabel: 'Weld seam',
    logisticsSpecSeamValue: 'Plexus technology',
    logisticsSpecLoadLabel: 'Load capacity',
    logisticsSpecLoadValue: 'up to 35 kg',
    logisticsSpecIndustryLabel: 'Segment',
    logisticsSpecIndustryValue: 'B2B export',

    categoryGreenhouseFilm: 'Greenhouse film',
    categoryShrinkFilm: 'Shrink film',
    categoryPolyethyleneBags: 'Polyethylene bags',
    categoryPetCapsules: 'PET capsules',
    categoryRoofingMaterials: 'Roofing materials',
    categoryBitumenMastic: 'Bitumen-polymer mastic',
    categoryPlainFilm: 'Standard film',
    categoryUvFilm: 'UV-protected film',
    categoryMultiLayerFilm: 'Multilayer film',
    categorySpecialFilm: 'Special film',
    categoryOther: 'Other',

    productInfo: 'PRODUCT INFO',
    allProducts: 'All products',
    price: 'Price',
    inStock: 'In stock',
    outOfStock: 'Out of stock',
    addToCart: 'Add to cart',
    addedToCart: 'Added to cart!',
    cartTitle: 'Cart',
    som: 'UZS',
    thickness: 'Thickness',
    width: 'Width',
    length: 'Length',
    quantity: 'Quantity',
    total: 'Total',
    checkout: 'Checkout',
    removeItem: 'Remove',
    orderSuccess: 'Order received!',
    orderSuccessDesc: 'Your order has been successfully placed. You can track order status in your profile.',
    goToProfile: 'Go to profile',
    continueShopping: 'Continue shopping',
    emptyCart: 'Cart is empty',
    emptyCartDesc: 'Browse products and add them to cart',
    viewProducts: 'View products',
    cartItemCount: 'items',
    orderSummary: 'Order summary',
    promoCode: 'Promo code',
    promoApplied: 'applied',
    productsLabel: 'Products',
    discount: 'Discount',
    shippingAddress: 'Shipping address',
    fullAddress: 'Full address',
    phoneNumber: 'Phone number',
    note: 'Note',
    additionalNote: 'Additional note...',
    sending: 'Sending...',
    loginAndOrder: 'Login & order',
    addressPhoneRequired: 'Address and phone number are required',
    ctaTitle: 'Direct from manufacturer for large orders',
    ctaDesc: 'Individual pricing, stable delivery, export documentation and logistics support — all in one place.',
    footerPhone: 'Phone',
    footerEmail: 'Email',
    footerAddress: 'Address',
    footerAddressValue: 'Tashkent, Uzbekistan',
    uvProtection: 'UV protection',
    viewImage: 'View image',

    heroSlide1Title: 'Higher Yields with Agro-Films',
    heroSlide1Subtitle: 'Premium films specially designed for greenhouses, protecting from UV rays and harsh weather conditions.',
    heroSlide2Title: 'Industrial Shrink Wrapping',
    heroSlide2Subtitle: 'Ensure 100% safety of your products during logistics. Strong and stretchable shrink films.',
    heroSlide3Title: 'Construction & Waterproofing',
    heroSlide3Subtitle: 'Reliably protect foundations and roofs from moisture with strong and thick coatings. With us, your structures last longer.',
    heroSlide4Title: 'Reliable & Eco-Friendly',
    heroSlide4Subtitle: 'Innovative packaging films, absolutely safe for the food industry. Keeps product freshness for a long time.',
    heroSlide5Title: 'Partnership & Stability',
    heroSlide5Subtitle: 'Join the distributor network across Uzbekistan. Quality film is the key to successful trade.',

    allNews: 'All news',
    feature: 'Feature',
    pressRelease: 'Press release',
    announcement: 'Announcement',
    article: 'Article',
    latestNews: 'Latest news',
    newsSubtitle: 'Company news and announcements',
    readMore: 'Read more',
    backToNews: 'Back to news',

    contactTitle: 'Contact us',
    contactSubtitle: 'If you have questions or want to place an order, contact us',
    address: 'Address',
    addressValue: 'Tashkent, Uchtepa district, Foziltepa street, 9',
    phone: 'Phone',
    email: 'Email',
    website: 'Website',
    workHours: 'Working hours',
    workHoursValue: 'Mon-Fri: 08:00 - 18:00',
    sendMessage: 'Send message',
    yourName: 'Your name',
    yourEmail: 'Your email',
    yourPhone: 'Your phone',
    message: 'Message',
    send: 'Send',

    loginTitle: 'Sign in',
    loginSubtitle: 'Sign in to your account',
    emailPlaceholder: 'email@example.com',
    password: 'Password',
    passwordPlaceholder: 'Your password',
    loggingIn: 'Signing in...',
    noAccount: "Don't have an account?",
    registerTitle: 'Register',
    registerSubtitle: 'Create a new account',
    name: 'Name',
    phonePlaceholder: '+998 90 123 45 67',
    haveAccount: 'Already have an account?',
    fullNamePlaceholder: 'Your full name',
    phoneLabel: 'Phone number',
    confirmPassword: 'Confirm password',
    confirmPasswordPlaceholder: 'Repeat password',
    minPasswordPlaceholder: 'At least 6 characters',
    registerLoading: 'Registering...',
    signIn: 'Sign in',
    passwordMismatch: 'Passwords do not match',
    passwordMinLength: 'Password must be at least 6 characters',

    footerDesc: 'Leading manufacturer of polyethylene film and packaging materials in Uzbekistan.',
    quickLinks: 'Quick links',
    contactInfo: 'Contact information',
    allRightsReserved: 'All rights reserved.',
    followUs: 'Social media',
    socialTelegram: 'Telegram',
    socialInstagram: 'Instagram',
    socialFacebook: 'Facebook',
    socialLinkedin: 'LinkedIn',

    statusPending: 'Pending',
    statusAccepted: 'Accepted',
    statusPreparing: 'Preparing',
    statusDelivered: 'Delivered',
    statusRollbackError: 'Cannot move order status back to an earlier stage',

    adminDashboard: 'Dashboard',
    adminProducts: 'Products',
    adminNews: 'News',
    adminOrders: 'Orders',
    adminUsers: 'Users',
    adminPromo: 'Promo codes',
    backToSite: 'Back to site',
    allStatuses: 'All statuses',
    orderNumber: 'Order #',
    customer: 'Customer',
    orderDate: 'Date',
    changeStatus: 'Change',
    noOrders: 'No orders',
    unknownUser: 'Unknown',
    productsInOrder: 'Products',
    amount: 'Amount',
    status: 'Status',
    dashboardTitle: 'Dashboard',
    analyticsTitle: 'Analytics',
    dataLoadError: 'Failed to load data',
    totalOrdersLabel: 'Total orders',
    deliveredOrdersLabel: 'Sales (delivered)',
    totalRevenueLabel: 'Total revenue (UZS)',
    totalUsersLabel: 'Total users',
    newUsersLabel: 'New users',
    totalProductsLabel: 'Total products',
    newProductsLabel: 'New products',
    diffShortLabel: 'diff',
    avgOrderLabel: 'Average order (UZS)',
    avgOrderValueLabel: 'Average order value',
    monthlyRevenueOrdersChart: 'Monthly revenue and orders',
    dailyRevenueChart: 'Daily revenue (30 days)',
    dailyOrdersChart: 'Daily orders (30 days)',
    orderStatusesChart: 'Order statuses',
    orderStatusesDistributionChart: 'Order status distribution',
    recentOrdersLabel: 'Recent orders',
    revenueLabel: 'Revenue (UZS)',
    ordersLabel: 'Orders',
    dailyRevenueLabel: 'Daily revenue',
    dailyOrdersCountLabel: 'Order count',
    selectPeriod: 'Select period',
    period1: 'Period 1',
    period2: 'Period 2',
    dateFrom: 'From',
    dateTo: 'To',
    compareLabel: 'Compare',
    compareDateFrom: 'Compare from',
    compareDateTo: 'To',
    applyFilter: 'Apply',
    resetFilter: 'Reset',
    totalCostLabel: 'Cost of goods (UZS)',
    realProfitLabel: 'Real profit (UZS)',
    profitMarginLabel: 'Profit margin',
    costLabel: 'Cost price',
    profitLabel: 'Profit',
    comparisonTitle: 'Period comparison',
    comparisonMetric: 'Metric',
    changeLabel: 'Change',
    prevPeriodOrders: 'Previous period orders',
    prevPeriodRevenue: 'Previous period revenue',
    prevPeriodCost: 'Previous period cost',
    prevPeriodProfit: 'Previous period profit',
    monthlyRevenueCostProfitChart: 'Monthly revenue, cost & profit',
    dailyRevenueCostChart: 'Daily revenue, cost & profit',
    footerBrandSubtitle: 'Premium polymer solutions',
    aboutHeroBadge: 'Operating since 2005',
    aboutHeroDesc: 'Since 2005, the company has been one of Central Asia\'s leading manufacturers of polyethylene and polymer materials. The plant was the first in Uzbekistan to launch 12-meter three-layer film production.',
    aboutHistoryBadge: 'History',
    aboutHistoryTitle: 'About the company',
    aboutStoryP1: 'Original Grand Plast MChJ was founded in Tashkent in 2005. Its core business is the production of polyethylene film and packaging materials. In its early years, the company specialized in a wide range of polyethylene products.',
    aboutStoryP2: 'In 2013, the company set a new benchmark for the industry by launching Uzbekistan\'s first production line for three-layer greenhouse film up to 12 meters wide. This technology made it possible to cover large greenhouses without seams and with greater durability.',
    aboutStoryP3: 'Our success is built on modern technology. Our production lines are equipped with advanced machinery from Spain, Korea, China, and Turkey. We use raw materials supplied by Repsol, Lotte Chemical, and Sinopec.',
    aboutStoryP4: 'We are also firmly established in waterproofing. Roll roofing materials and bitumen-polymer mastics produced under the ROOF COVER brand are recognized as a quality benchmark in the construction market.',
    aboutMilestone1Title: 'Foundation',
    aboutMilestone1Desc: 'Polyethylene product manufacturing was launched in Tashkent.',
    aboutMilestone2Title: '12-meter record',
    aboutMilestone2Desc: 'Uzbekistan\'s first 12-meter three-layer greenhouse film production was launched.',
    aboutMilestone3Label: 'Global',
    aboutMilestone3Title: 'International partnership',
    aboutMilestone3Desc: 'Stable cooperation was established with international suppliers including Repsol, Lotte, and Sinopec.',
    aboutSummaryMeta: 'Since 2005 | Tashkent',
    aboutSummaryBadge: 'No.1 greenhouse film in Uzbekistan',
    aboutActivitiesBadge: 'Operations',
    aboutActivitiesTitle: 'Core directions',
    aboutActivity1Title: 'Greenhouse film',
    aboutActivity1Desc: 'Three-layer polyethylene film resistant to intense UV exposure. Available in widths up to 12 meters.',
    aboutActivity2Title: 'Shrink film',
    aboutActivity2Desc: 'Used for tight and reliable packaging after heat treatment.',
    aboutActivity3Title: 'Polyethylene bags',
    aboutActivity3Desc: 'Vacuum cash bags for banks and various bag formats for daily use.',
    aboutActivity4Title: 'PET capsules',
    aboutActivity4Desc: 'Cap materials for water and oil containers ranging from 28 to 140 grams.',
    aboutActivity5Title: 'Waterproofing',
    aboutActivity5Desc: 'Roll roofing and waterproofing materials designed for heat and cold resistance with long service life.',
    aboutActivity6Title: 'Bitumen-polymer mastic',
    aboutActivity6Desc: 'High-adhesion polymer mastics for waterproofing and sealing works.',
    aboutValuesBadge: 'Values',
    aboutValuesTitle: 'Mission and goals',
    aboutValue1Title: 'Our mission',
    aboutValue1Desc: 'To provide useful and cost-effective packaging solutions using modern technology and quality raw materials.',
    aboutValue2Title: 'Our values',
    aboutValue2Desc: 'Quality, reliability, and innovation. We aim to build long-term cooperation with every partner.',
    aboutValue3Title: 'Ecology',
    aboutValue3Desc: 'We focus on reducing waste and improving recycling opportunities.',
    aboutValue4Title: 'Individual approach',
    aboutValue4Desc: 'We work with each client individually and offer special pricing for large-volume orders.',
    aboutContactBadge: 'Contact',
    aboutContactTitle: 'Get in touch',
    aboutContactSubtitle: 'If you have questions or want to place an order, contact us.',
    aboutMapTitle: 'Original Grand Plast address',
    aboutContactAddressLabel: 'Address',
    aboutContactAddressValue: '9 Foziltepa Street, Uchtepa District, Tashkent',
    aboutContactPhone1Label: 'Phone',
    aboutContactPhone2Label: 'Phone 2',
    aboutContactPhone3Label: 'Phone 3',
    aboutContactEmailLabel: 'Email',
    aboutContactWebsiteLabel: 'Website',
    aboutContactHoursLabel: 'Working hours',
    aboutContactHoursValue: 'Mon-Fri: 08:00 - 18:00',
    aboutCtaTitle: 'Ready to cooperate?',
    aboutCtaDesc: 'Call us for detailed information about products, prices, and delivery.',
    aboutCtaButton: 'Call now',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('grandplast-lang') || 'uz');

  const changeLanguage = useCallback((lang) => {
    setLanguage(lang);
    localStorage.setItem('grandplast-lang', lang);
  }, []);

  const t = useCallback((key) => {
    return translations[language]?.[key] || translations.en[key] || translations.uz[key] || key;
  }, [language]);

  const tl = useCallback((obj, field) => {
    if (!obj) return '';
    const candidateKeys = [
      `${field}_${language}`,
      `${field}_en`,
      `${field}_ru`,
      `${field}_uz`,
      field,
    ];

    for (const key of candidateKeys) {
      const value = obj[key];
      if (typeof value === 'string' && value.trim()) return value.trim();
    }
    return '';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, tl }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
