import { createContext, useCallback, useContext, useState } from 'react';

const translations = {
  uz: {
    home: 'Bosh sahifa',
    about: 'Biz haqimizda',
    products: 'Mahsulotlar',
    news: 'Yangiliklar',
    promotions: 'Aksiyalar',
    contacts: 'Kontaktlar',
    login: 'Kirish',
    register: "Ro'yxatdan o'tish",
    cart: 'Savatcha',
    profile: 'Profil',
    search: 'Qidirish...',
    adminPanel: 'Admin panel',
    logout: 'Chiqish',

    heroTitle1: 'Sanoat va agrosanoat uchun',
    heroTitle2: 'innovatsion polimer',
    heroTitle3: 'yechimlar',
    heroSubtitle: "2005-yildan buyon Markaziy Osiyo bozori uchun yuqori sifatli polimer mahsulotlari ishlab chiqaramiz.",

    techSolutions: 'Texnologik yechimlar',
    techDesc: "Global sanoat talablariga mos, yuqori fizik-mexanik ko'rsatkichli polimer mahsulotlar.",
    agroTitle: 'Agrosanoat komplekslari',
    thermoTitle: 'Termo qadoqlash (Shrink)',
    logisticsTitle: 'Sanoat logistika paketlari',
    moreParams: 'Batafsil parametrlar',
    onlineCatalog: 'Onlayn katalog',
    fullList: "To'liq ro'yxat",
    partnersTitle: 'Hamkorlar',

    b2bOffer: 'Katta hajmdagi B2B xaridlar uchun maxsus taklif',
    b2bDesc: '"Original Grand Plast" dilerlar, fermerlar va eksportyorlar uchun qulay shartlarda hamkorlikni taklif qiladi.',
    requestOffer: "Kommersiya taklifini so'rash",
    headOffice: 'Bosh ofis',
    b2bBenefit1: 'Individual narx va uzoq muddatli kontrakt',
    b2bBenefit2: 'Eksport hujjatlari va logistika yordami',
    b2bBenefit3: '24/7 shaxsiy menejer va tez aloqa',
    b2bBenefit4: 'Kafolatlangan sifat va barqaror yetkazib berish',

    agroDesc: "100-200 mikron oralig'idagi ko'p qatlamli UV, IR va EVA qo'shimchali plyonkalar ishlab chiqaramiz.",
    agroSpecWidthLabel: 'Maksimal kenglik',
    agroSpecWidthValue: '12 metrgacha',
    agroSpecUvLabel: 'UV kafolat',
    agroSpecUvValue: '3-5 yil',
    agroSpecLightLabel: "Yorug'lik o'tkazuvchanlik",
    agroSpecLightValue: '88-92%',
    thermoDesc: "Guruhli va palletli qadoqlash uchun mo'ljallangan texnik plyonkalar.",
    thermoSpecStretchLabel: "Uzilishdagi cho'zilish",
    thermoSpecStretchValue: '>= 350% MD',
    thermoSpecShrinkLabel: 'Termik siqilish',
    thermoSpecShrinkValue: 'T 50-70% / K 30-50%',
    thermoSpecDensityLabel: 'Zichlik',
    thermoSpecDensityValue: '0.925 g/cm3',
    logisticsDesc: "Og'ir yuklar uchun xavfsiz va mustahkam ekstrudirovka qilingan polimer materiallar.",
    logisticsSpecSeamLabel: 'Payvand choki',
    logisticsSpecSeamValue: 'Plexus texnologiyasi',
    logisticsSpecLoadLabel: 'Chidamli yuk',
    logisticsSpecLoadValue: '35 kggacha',
    logisticsSpecIndustryLabel: 'Soha',
    logisticsSpecIndustryValue: 'B2B eksport',

    categoryGreenhouseFilm: 'Issiqxona plyonkasi',
    categoryShrinkFilm: 'Termo-usadoz plyonka',
    categoryPolyethyleneBags: 'Polietilen paketlar',
    categoryPetCapsules: 'PET kapsulalar',
    categoryRoofingMaterials: 'Tom yopish materiallari',
    categoryBitumenMastic: 'Bitum-polimer mastika',
    categoryPlainFilm: 'Oddiy plyonka',
    categoryUvFilm: 'UV himoyali',
    categoryMultiLayerFilm: "Ko'p qavatli",
    categorySpecialFilm: 'Maxsus plyonka',
    categoryOther: 'Boshqa',

    productInfo: "MAHSULOT HAQIDA",
    allProducts: 'Barcha mahsulotlar',
    price: 'Narx',
    inStock: 'Mavjud',
    outOfStock: "Mavjud emas",
    addToCart: "Savatga qo'shish",
    addedToCart: "Savatga qo'shildi!",
    cartTitle: 'Savatcha',
    som: "so'm",
    thickness: 'Qalinlik',
    width: 'Eni',
    length: 'Uzunlik',
    quantity: 'Miqdor',
    total: 'Jami',
    checkout: 'Buyurtma berish',
    removeItem: "O'chirish",

    allNews: 'Barcha yangiliklar',
    feature: 'Yangilik',
    pressRelease: 'Press-reliz',
    announcement: "E'lon",
    article: 'Maqola',
    latestNews: "So'nggi yangiliklar",
    newsSubtitle: "Korxona yangiliklari va e'lonlari",
    readMore: "Batafsil o'qish",
    backToNews: 'Yangiliklarga qaytish',

    contactTitle: "Biz bilan bog'laning",
    contactSubtitle: "Savollaringiz bo'lsa yoki buyurtma bermoqchi bo'lsangiz, murojaat qiling",
    address: 'Manzil',
    addressValue: "Toshkent sh., Uchtepa tumani, Foziltepa ko'chasi, 9-uy",
    phone: 'Telefon',
    email: 'Email',
    website: 'Veb-sayt',
    workHours: 'Ish vaqti',
    workHoursValue: 'Du-Ju: 08:00 - 18:00',
    sendMessage: 'Xabar yuborish',
    yourName: 'Ismingiz',
    yourEmail: 'Email manzilingiz',
    yourPhone: 'Telefon raqamingiz',
    message: 'Xabaringiz',
    send: 'Yuborish',

    loginTitle: 'Tizimga kirish',
    loginSubtitle: 'Hisobingizga kiring va xarid qiling',
    emailPlaceholder: 'email@misol.uz',
    password: 'Parol',
    passwordPlaceholder: 'Parolingiz',
    loggingIn: 'Kirilmoqda...',
    noAccount: "Hisobingiz yo'qmi?",
    registerTitle: "Ro'yxatdan o'tish",
    registerSubtitle: 'Yangi hisob yarating',
    name: 'Ism',
    phonePlaceholder: '+998 90 123 45 67',
    haveAccount: 'Hisobingiz bormi?',
    fullNamePlaceholder: "To'liq ismingiz",
    phoneLabel: 'Telefon raqam',
    confirmPassword: 'Parolni tasdiqlash',
    confirmPasswordPlaceholder: 'Parolni qayta kiriting',
    minPasswordPlaceholder: 'Kamida 6 belgi',
    registerLoading: "Ro'yxatdan o'tilmoqda...",
    signIn: 'Kirish',
    passwordMismatch: 'Parollar mos kelmaydi',
    passwordMinLength: "Parol kamida 6 belgidan iborat bo'lishi kerak",

    footerDesc: "O'zbekistonda polietilen plyonka va qadoqlash materiallari ishlab chiqaruvchi yetakchi korxona.",
    quickLinks: 'Tezkor havolalar',
    contactInfo: "Aloqa ma'lumotlari",
    allRightsReserved: 'Barcha huquqlar himoyalangan.',
    followUs: 'Ijtimoiy tarmoqlar',
    socialTelegram: 'Telegram',
    socialInstagram: 'Instagram',
    socialFacebook: 'Facebook',
    socialLinkedin: 'LinkedIn',

    statusPending: 'Kutilmoqda',
    statusAccepted: 'Qabul qilindi',
    statusPreparing: 'Tayyorlanmoqda',
    statusDelivered: 'Yetkazildi',
    statusRollbackError: "Statusni avvalgi bosqichga qaytarib bo'lmaydi",

    adminDashboard: 'Dashboard',
    adminProducts: 'Mahsulotlar',
    adminNews: 'Yangiliklar',
    adminOrders: 'Buyurtmalar',
    adminUsers: 'Foydalanuvchilar',
    adminPromo: 'Promokodlar',
    backToSite: 'Saytga qaytish',
    allStatuses: 'Barcha statuslar',
    orderNumber: 'Raqam',
    customer: 'Mijoz',
    orderDate: 'Sana',
    changeStatus: "O'zgartirish",
    noOrders: "Buyurtmalar yo'q",
    unknownUser: "Noma'lum",
    productsInOrder: 'Mahsulotlar',
    amount: 'Jami',
    status: 'Status',
    dashboardTitle: 'Dashboard',
    analyticsTitle: 'Analitika',
    dataLoadError: "Ma'lumot yuklanmadi",
    totalOrdersLabel: 'Jami buyurtmalar',
    totalRevenueLabel: "Jami daromad (so'm)",
    totalUsersLabel: 'Jami foydalanuvchilar',
    totalProductsLabel: 'Jami mahsulotlar',
    avgOrderLabel: "O'rtacha buyurtma (so'm)",
    avgOrderValueLabel: "O'rtacha buyurtma qiymati",
    monthlyRevenueOrdersChart: 'Oylik daromad va buyurtmalar',
    dailyRevenueChart: 'Kunlik daromad (30 kun)',
    dailyOrdersChart: 'Kunlik buyurtmalar (30 kun)',
    orderStatusesChart: 'Buyurtma statuslari',
    orderStatusesDistributionChart: 'Buyurtma statuslari taqsimoti',
    recentOrdersLabel: "So'nggi buyurtmalar",
    revenueLabel: "Daromad (so'm)",
    ordersLabel: 'Buyurtmalar',
    dailyRevenueLabel: 'Kunlik daromad',
    dailyOrdersCountLabel: 'Buyurtmalar soni',
  },
  ru: {
    home: 'Главная',
    about: 'О нас',
    products: 'Продукция',
    news: 'Новости',
    promotions: 'Акции',
    contacts: 'Контакты',
    login: 'Войти',
    register: 'Регистрация',
    cart: 'Корзина',
    profile: 'Профиль',
    search: 'Поиск...',
    adminPanel: 'Админ панель',
    logout: 'Выйти',

    heroTitle1: 'Для промышленности и агросектора',
    heroTitle2: 'инновационные полимерные',
    heroTitle3: 'решения',
    heroSubtitle: 'С 2005 года производим качественные полимерные материалы для рынка Центральной Азии.',

    techSolutions: 'Технологические решения',
    techDesc: 'Полимерные материалы с высокими физико-механическими показателями по международным стандартам.',
    agroTitle: 'Агропромышленные комплексы',
    thermoTitle: 'Термоусадочная упаковка (Shrink)',
    logisticsTitle: 'Промышленные логистические пакеты',
    moreParams: 'Подробнее',
    onlineCatalog: 'Онлайн каталог',
    fullList: 'Полный список',
    partnersTitle: 'Партнеры',

    b2bOffer: 'Специальное предложение для крупных B2B закупок',
    b2bDesc: '"Original Grand Plast" предлагает выгодные условия для дилеров, фермеров и экспортёров.',
    requestOffer: 'Запросить коммерческое предложение',
    headOffice: 'Головной офис',
    b2bBenefit1: 'Индивидуальные цены и долгосрочный контракт',
    b2bBenefit2: 'Экспортные документы и логистическая поддержка',
    b2bBenefit3: 'Персональный менеджер 24/7',
    b2bBenefit4: 'Гарантированное качество и стабильные поставки',

    agroDesc: 'Производим многослойные пленки 100-200 микрон с добавками UV, IR и EVA.',
    agroSpecWidthLabel: 'Максимальная ширина',
    agroSpecWidthValue: 'до 12 метров',
    agroSpecUvLabel: 'UV гарантия',
    agroSpecUvValue: '3-5 лет',
    agroSpecLightLabel: 'Светопропускание',
    agroSpecLightValue: '88-92%',
    thermoDesc: 'Технические пленки для групповой и паллетной упаковки на автоматических линиях.',
    thermoSpecStretchLabel: 'Удлинение при разрыве',
    thermoSpecStretchValue: '>= 350% MD',
    thermoSpecShrinkLabel: 'Термоусадка',
    thermoSpecShrinkValue: 'T 50-70% / K 30-50%',
    thermoSpecDensityLabel: 'Плотность',
    thermoSpecDensityValue: '0.925 g/cm3',
    logisticsDesc: 'Экструдированные полимерные материалы для тяжелой логистики.',
    logisticsSpecSeamLabel: 'Сварной шов',
    logisticsSpecSeamValue: 'Технология Plexus',
    logisticsSpecLoadLabel: 'Нагрузка',
    logisticsSpecLoadValue: 'до 35 кг',
    logisticsSpecIndustryLabel: 'Сегмент',
    logisticsSpecIndustryValue: 'B2B экспорт',

    categoryGreenhouseFilm: 'Тепличная пленка',
    categoryShrinkFilm: 'Термоусадочная пленка',
    categoryPolyethyleneBags: 'Полиэтиленовые пакеты',
    categoryPetCapsules: 'ПЭТ капсулы',
    categoryRoofingMaterials: 'Кровельные материалы',
    categoryBitumenMastic: 'Битумно-полимерная мастика',
    categoryPlainFilm: 'Обычная пленка',
    categoryUvFilm: 'С UV защитой',
    categoryMultiLayerFilm: 'Многослойная',
    categorySpecialFilm: 'Специальная пленка',
    categoryOther: 'Другое',

    productInfo: 'О ПРОДУКТЕ',
    allProducts: 'Все продукты',
    price: 'Цена',
    inStock: 'В наличии',
    outOfStock: 'Нет в наличии',
    addToCart: 'В корзину',
    addedToCart: 'Добавлено в корзину!',
    cartTitle: 'Корзина',
    som: 'сум',
    thickness: 'Толщина',
    width: 'Ширина',
    length: 'Длина',
    quantity: 'Количество',
    total: 'Итого',
    checkout: 'Оформить заказ',
    removeItem: 'Удалить',

    allNews: 'Все новости',
    feature: 'Новость',
    pressRelease: 'Пресс-релиз',
    announcement: 'Объявление',
    article: 'Статья',
    latestNews: 'Последние новости',
    newsSubtitle: 'Новости и объявления компании',
    readMore: 'Подробнее',
    backToNews: 'Назад к новостям',

    contactTitle: 'Свяжитесь с нами',
    contactSubtitle: 'Если у вас есть вопросы или вы хотите оформить заказ, свяжитесь с нами',
    address: 'Адрес',
    addressValue: 'г. Ташкент, Учтепинский район, ул. Фозилтепа, дом 9',
    phone: 'Телефон',
    email: 'Email',
    website: 'Веб-сайт',
    workHours: 'Режим работы',
    workHoursValue: 'Пн-Пт: 08:00 - 18:00',
    sendMessage: 'Отправить сообщение',
    yourName: 'Ваше имя',
    yourEmail: 'Ваш email',
    yourPhone: 'Ваш телефон',
    message: 'Сообщение',
    send: 'Отправить',

    loginTitle: 'Вход',
    loginSubtitle: 'Войдите в аккаунт для покупок',
    emailPlaceholder: 'email@example.com',
    password: 'Пароль',
    passwordPlaceholder: 'Ваш пароль',
    loggingIn: 'Вход...',
    noAccount: 'Нет аккаунта?',
    registerTitle: 'Регистрация',
    registerSubtitle: 'Создайте новый аккаунт',
    name: 'Имя',
    phonePlaceholder: '+998 90 123 45 67',
    haveAccount: 'Уже есть аккаунт?',
    fullNamePlaceholder: 'Ваше полное имя',
    phoneLabel: 'Номер телефона',
    confirmPassword: 'Подтвердите пароль',
    confirmPasswordPlaceholder: 'Повторите пароль',
    minPasswordPlaceholder: 'Минимум 6 символов',
    registerLoading: 'Регистрация...',
    signIn: 'Войти',
    passwordMismatch: 'Пароли не совпадают',
    passwordMinLength: 'Пароль должен содержать минимум 6 символов',

    footerDesc: 'Ведущее предприятие по производству полиэтиленовой пленки и упаковочных материалов в Узбекистане.',
    quickLinks: 'Быстрые ссылки',
    contactInfo: 'Контактная информация',
    allRightsReserved: 'Все права защищены.',
    followUs: 'Социальные сети',
    socialTelegram: 'Telegram',
    socialInstagram: 'Instagram',
    socialFacebook: 'Facebook',
    socialLinkedin: 'LinkedIn',

    statusPending: 'Ожидается',
    statusAccepted: 'Принят',
    statusPreparing: 'Готовится',
    statusDelivered: 'Доставлен',
    statusRollbackError: 'Нельзя вернуть заказ на предыдущий статус',

    adminDashboard: 'Дашборд',
    adminProducts: 'Продукты',
    adminNews: 'Новости',
    adminOrders: 'Заказы',
    adminUsers: 'Пользователи',
    adminPromo: 'Промокоды',
    backToSite: 'Вернуться на сайт',
    allStatuses: 'Все статусы',
    orderNumber: 'Номер',
    customer: 'Клиент',
    orderDate: 'Дата',
    changeStatus: 'Изменение',
    noOrders: 'Заказов нет',
    unknownUser: 'Неизвестно',
    productsInOrder: 'Товары',
    amount: 'Сумма',
    status: 'Статус',
    dashboardTitle: 'Дашборд',
    analyticsTitle: 'Аналитика',
    dataLoadError: 'Не удалось загрузить данные',
    totalOrdersLabel: 'Всего заказов',
    totalRevenueLabel: 'Общая выручка (сум)',
    totalUsersLabel: 'Всего пользователей',
    totalProductsLabel: 'Всего товаров',
    avgOrderLabel: 'Средний заказ (сум)',
    avgOrderValueLabel: 'Средний чек',
    monthlyRevenueOrdersChart: 'Месячная выручка и заказы',
    dailyRevenueChart: 'Дневная выручка (30 дней)',
    dailyOrdersChart: 'Дневные заказы (30 дней)',
    orderStatusesChart: 'Статусы заказов',
    orderStatusesDistributionChart: 'Распределение статусов заказов',
    recentOrdersLabel: 'Последние заказы',
    revenueLabel: 'Выручка (сум)',
    ordersLabel: 'Заказы',
    dailyRevenueLabel: 'Дневная выручка',
    dailyOrdersCountLabel: 'Количество заказов',
  },
  en: {
    home: 'Home',
    about: 'About',
    products: 'Products',
    news: 'News',
    promotions: 'Promotions',
    contacts: 'Contacts',
    login: 'Login',
    register: 'Register',
    cart: 'Cart',
    profile: 'Profile',
    search: 'Search...',
    adminPanel: 'Admin Panel',
    logout: 'Logout',

    heroTitle1: 'For industry and agriculture',
    heroTitle2: 'innovative polymer',
    heroTitle3: 'solutions',
    heroSubtitle: 'Since 2005, we have produced high-quality polymer materials for the Central Asian market.',

    techSolutions: 'Technological solutions',
    techDesc: 'Polymer materials with high physical and mechanical performance, aligned with global standards.',
    agroTitle: 'Agro-industrial complexes',
    thermoTitle: 'Shrink packaging',
    logisticsTitle: 'Industrial logistics packaging',
    moreParams: 'More details',
    onlineCatalog: 'Online catalog',
    fullList: 'Full list',
    partnersTitle: 'Partners',

    b2bOffer: 'Special offer for large B2B purchases',
    b2bDesc: '"Original Grand Plast" offers favorable terms for dealers, farms, and exporters.',
    requestOffer: 'Request commercial offer',
    headOffice: 'Head office',
    b2bBenefit1: 'Individual pricing and long-term contracts',
    b2bBenefit2: 'Export documentation and logistics support',
    b2bBenefit3: 'Dedicated 24/7 account manager',
    b2bBenefit4: 'Guaranteed quality and stable supply',

    agroDesc: 'We produce 100-200 micron multilayer films with UV, IR, and EVA additives.',
    agroSpecWidthLabel: 'Maximum width',
    agroSpecWidthValue: 'up to 12 meters',
    agroSpecUvLabel: 'UV warranty',
    agroSpecUvValue: '3-5 years',
    agroSpecLightLabel: 'Light transmission',
    agroSpecLightValue: '88-92%',
    thermoDesc: 'Technical films for grouped and pallet packaging on automated lines.',
    thermoSpecStretchLabel: 'Elongation at break',
    thermoSpecStretchValue: '>= 350% MD',
    thermoSpecShrinkLabel: 'Thermal shrinkage',
    thermoSpecShrinkValue: 'T 50-70% / K 30-50%',
    thermoSpecDensityLabel: 'Density',
    thermoSpecDensityValue: '0.925 g/cm3',
    logisticsDesc: 'Extruded polymer materials for heavy-duty logistics.',
    logisticsSpecSeamLabel: 'Weld seam',
    logisticsSpecSeamValue: 'Plexus technology',
    logisticsSpecLoadLabel: 'Load capacity',
    logisticsSpecLoadValue: 'up to 35 kg',
    logisticsSpecIndustryLabel: 'Segment',
    logisticsSpecIndustryValue: 'B2B export',

    categoryGreenhouseFilm: 'Greenhouse film',
    categoryShrinkFilm: 'Shrink film',
    categoryPolyethyleneBags: 'Polyethylene bags',
    categoryPetCapsules: 'PET capsules',
    categoryRoofingMaterials: 'Roofing materials',
    categoryBitumenMastic: 'Bitumen-polymer mastic',
    categoryPlainFilm: 'Standard film',
    categoryUvFilm: 'UV-protected film',
    categoryMultiLayerFilm: 'Multilayer film',
    categorySpecialFilm: 'Special film',
    categoryOther: 'Other',

    productInfo: 'PRODUCT INFO',
    allProducts: 'All products',
    price: 'Price',
    inStock: 'In stock',
    outOfStock: 'Out of stock',
    addToCart: 'Add to cart',
    addedToCart: 'Added to cart!',
    cartTitle: 'Cart',
    som: 'UZS',
    thickness: 'Thickness',
    width: 'Width',
    length: 'Length',
    quantity: 'Quantity',
    total: 'Total',
    checkout: 'Checkout',
    removeItem: 'Remove',

    allNews: 'All news',
    feature: 'Feature',
    pressRelease: 'Press release',
    announcement: 'Announcement',
    article: 'Article',
    latestNews: 'Latest news',
    newsSubtitle: 'Company news and announcements',
    readMore: 'Read more',
    backToNews: 'Back to news',

    contactTitle: 'Contact us',
    contactSubtitle: 'If you have questions or want to place an order, contact us',
    address: 'Address',
    addressValue: 'Tashkent, Uchtepa district, Foziltepa street, 9',
    phone: 'Phone',
    email: 'Email',
    website: 'Website',
    workHours: 'Working hours',
    workHoursValue: 'Mon-Fri: 08:00 - 18:00',
    sendMessage: 'Send message',
    yourName: 'Your name',
    yourEmail: 'Your email',
    yourPhone: 'Your phone',
    message: 'Message',
    send: 'Send',

    loginTitle: 'Sign in',
    loginSubtitle: 'Sign in to your account',
    emailPlaceholder: 'email@example.com',
    password: 'Password',
    passwordPlaceholder: 'Your password',
    loggingIn: 'Signing in...',
    noAccount: "Don't have an account?",
    registerTitle: 'Register',
    registerSubtitle: 'Create a new account',
    name: 'Name',
    phonePlaceholder: '+998 90 123 45 67',
    haveAccount: 'Already have an account?',
    fullNamePlaceholder: 'Your full name',
    phoneLabel: 'Phone number',
    confirmPassword: 'Confirm password',
    confirmPasswordPlaceholder: 'Repeat password',
    minPasswordPlaceholder: 'At least 6 characters',
    registerLoading: 'Registering...',
    signIn: 'Sign in',
    passwordMismatch: 'Passwords do not match',
    passwordMinLength: 'Password must be at least 6 characters',

    footerDesc: 'Leading manufacturer of polyethylene film and packaging materials in Uzbekistan.',
    quickLinks: 'Quick links',
    contactInfo: 'Contact information',
    allRightsReserved: 'All rights reserved.',
    followUs: 'Social media',
    socialTelegram: 'Telegram',
    socialInstagram: 'Instagram',
    socialFacebook: 'Facebook',
    socialLinkedin: 'LinkedIn',

    statusPending: 'Pending',
    statusAccepted: 'Accepted',
    statusPreparing: 'Preparing',
    statusDelivered: 'Delivered',
    statusRollbackError: 'Cannot move order status back to an earlier stage',

    adminDashboard: 'Dashboard',
    adminProducts: 'Products',
    adminNews: 'News',
    adminOrders: 'Orders',
    adminUsers: 'Users',
    adminPromo: 'Promo codes',
    backToSite: 'Back to site',
    allStatuses: 'All statuses',
    orderNumber: 'Order #',
    customer: 'Customer',
    orderDate: 'Date',
    changeStatus: 'Change',
    noOrders: 'No orders',
    unknownUser: 'Unknown',
    productsInOrder: 'Products',
    amount: 'Amount',
    status: 'Status',
    dashboardTitle: 'Dashboard',
    analyticsTitle: 'Analytics',
    dataLoadError: 'Failed to load data',
    totalOrdersLabel: 'Total orders',
    totalRevenueLabel: 'Total revenue (UZS)',
    totalUsersLabel: 'Total users',
    totalProductsLabel: 'Total products',
    avgOrderLabel: 'Average order (UZS)',
    avgOrderValueLabel: 'Average order value',
    monthlyRevenueOrdersChart: 'Monthly revenue and orders',
    dailyRevenueChart: 'Daily revenue (30 days)',
    dailyOrdersChart: 'Daily orders (30 days)',
    orderStatusesChart: 'Order statuses',
    orderStatusesDistributionChart: 'Order status distribution',
    recentOrdersLabel: 'Recent orders',
    revenueLabel: 'Revenue (UZS)',
    ordersLabel: 'Orders',
    dailyRevenueLabel: 'Daily revenue',
    dailyOrdersCountLabel: 'Order count',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('grandplast-lang') || 'uz');

  const changeLanguage = useCallback((lang) => {
    setLanguage(lang);
    localStorage.setItem('grandplast-lang', lang);
  }, []);

  const t = useCallback((key) => {
    return translations[language]?.[key] || translations.en[key] || translations.uz[key] || key;
  }, [language]);

  const tl = useCallback((obj, field) => {
    if (!obj) return '';
    const candidateKeys = [
      `${field}_${language}`,
      `${field}_en`,
      `${field}_ru`,
      `${field}_uz`,
      field,
    ];

    for (const key of candidateKeys) {
      const value = obj[key];
      if (typeof value === 'string' && value.trim()) return value.trim();
    }
    return '';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, tl }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
